### ISSUE TITLE
applesfera.com

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [cliqz-oss/autoconsent#4]
Cookie popup not blocked

CSS rule proposed: .cookies-overlay

![Captura de Pantalla 2019-12-01 a la(s) 07 31 27](https://user-images.githubusercontent.com/57176665/69912772-9f1f1980-140c-11ea-9750-06b81dfac669.png)

**Comment by Lucas-Di-Tomase** [comment]
This also happens on xataka.com (because these sites apparently belong to the same company)

**Comment by Lucas-Di-Tomase** [comment]
How long are updates supposed to take till they reach end users? I am asking because it is not fixed  on my end and it has been 2 days since this issue was closed. Thanks.

**Comment by Lucas-Di-Tomase** [comment]
![Captura de Pantalla 2019-12-18 a la(s) 12 47 57](https://user-images.githubusercontent.com/57176665/71100941-a7a97b00-2194-11ea-9169-a0232db04435.png)

**Comment by sammacbeth** [comment]
They're currently being tested internally, and we will push the updates to all users shortly.

**Comment by sammacbeth** [comment]
Note these were pushed out to all users last week, so should be live for you now.

**Comment by Lucas-Di-Tomase** [comment]
This issue began to reappear some time ago so I am reopening this isssue. For some time it was fixed but then it began appearing again. I can confirm in the ruleset that the CSS rule were added properly and by using AdGuard with those same rules I see the problem is fixed, but for some reason Cliqz is not applying the rules accordingly and thus the cookie popup is still visible
